# Generated by Django 4.2 on 2025-01-12 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher_subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('letter', models.CharField(choices=[('A', 'А'), ('B', 'Б'), ('W', 'В'), ('G', 'Г'), ('MA', 'МА'), ('MB', 'МБ'), ('MW', 'МВ'), ('MG', 'МГ')], max_length=2)),
                ('organiser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_subject.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('birthday_day', models.DateField(null=True)),
                ('group', models.CharField(choices=[('ONE', '1'), ('TWO', '2')], max_length=3)),
                ('clas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_class.class')),
            ],
        ),
    ]
