# Generated by Django 4.2 on 2025-01-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_class', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
