# Generated by Django 4.2 on 2025-01-12 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('third_name', models.CharField(max_length=255)),
                ('birthday_day', models.DateField(null=True)),
                ('role', models.CharField(choices=[('HEAD_TEACHER', 'директор'), ('HELP_HEAD_TEACHER', 'зауч'), ('USUALLY_TEACHER', 'просто вчитель')], default='USUALLY_TEACHER', max_length=30)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher_subject.subject')),
            ],
        ),
    ]
