# Generated by Django 4.2 on 2025-01-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
