# Generated by Django 4.2 on 2025-01-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_subject', '0002_alter_teacher_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birthday_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
